version: '3.8'

services:
  chroma:
    image: chromadb/chroma
    ports:
      - "${CHROMA_PORT}:8000"
    volumes:
      - chroma_data:/chroma/chroma/
      - ./server.htpasswd:/auth/server.htpasswd:ro
    environment:
      - CHROMA_SERVER_AUTHN_PROVIDER=${CHROMA_SERVER_AUTHN_PROVIDER}
      - CHROMA_SERVER_AUTHN_CREDENTIALS_FILE=${CHROMA_SERVER_AUTHN_CREDENTIALS_FILE}

volumes:
  chroma_data:
    driver: local