[project]
name = "mafia-assistant-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=0.5.23",
    "ipykernel>=6.29.5",
    "pydantic>=2.10.3",
]
